### PR TITLE
Project-naming standard convention

### PR DESCRIPTION
**Pull request by kdaud**
Added docs in the code base!

### CODE REVIEW

**Comment by kdaud** [comment]
Hey dev! Are you still reviewing this PR (pull request)!
cc: @PyGamma

**Review by PyGamma — CHANGES_REQUESTED** [review]
Love the code especially the core contributor section, now you are missing a multiline comment, for example, you closed a multiline commenting at line 28 and open another comment at line 30 without writing a code in between them. it would be appropriate if you didn't close it.

**Comment by kdaud** [comment]
Hey @PyGamma  thanks for reviewing my work. Am currently offline. When I get connected I will address the comment in the best possible way

**Comment by kdaud** [comment]
> 
> 
> Love the code especially the core contributor section, now you are missing a multiline comment, for example, you closed a multiline commenting at line 28 and open another comment at line 30 without writing a code in between them. it would be appropriate if you didn't close it.

Hey @PyGamma thanks for reviewing my work. Am currently offline. When I get connected I will address the comment in the best possible way

**Pull request closed without merging**
